from flask import Flask, render_template, request, redirect
import sqlite3
import random
import string
import re
from urllib.parse import urlparse

app = Flask(__name__)

DATABASE = "database.db"

# URL Normalization
def normalize_url(url):
    url = url.strip()

    if not url.startswith(("http://", "https://")):
        url = "https://" + url
    parsed = urlparse(url)
    domain = parsed.netloc.lower()

    if domain.startswith("www."):
        domain = domain[4:]
    path = parsed.path.rstrip("/")

    if not path:
        path = "/"
    normalized = f"{parsed.scheme}://{domain}{path}"

    if parsed.query:
        normalized += f"?{parsed.query}"
    return normalized

# URL Validation
def is_valid_url(url):
    try:
        parsed = urlparse(url)

        if not parsed.scheme or not parsed.netloc:
            return False

        # Must contain a dot (.)
        if "." not in parsed.netloc:
            return False
        return True

    except Exception:
        return False
    
# Database Initialization
def init_db():

    with sqlite3.connect(DATABASE) as conn:
        cursor = conn.cursor()
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS urls (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                original_url TEXT NOT NULL,
                short_code TEXT UNIQUE NOT NULL,
                clicks INTEGER DEFAULT 0
            )
        """)
        cursor.execute("""
            CREATE UNIQUE INDEX IF NOT EXISTS idx_shortcode
            ON urls(short_code)
        """)
        conn.commit()

# Generate Random Short Code
def generate_short_code(length=6):
    characters = string.ascii_letters + string.digits
    return ''.join(random.choice(characters) for _ in range(length))

# Home Page
@app.route('/', methods=['GET', 'POST'])
def home():

    short_url = None
    message = ""
    if request.method == 'POST':

        original_url = normalize_url(request.form['url'])
        custom_code = request.form.get('custom_code', '').strip()

        # Validate URL
        if not is_valid_url(original_url):
            return render_template(
                'index.html',
                error_message="Please enter a valid URL."
            ), 400

        # Prevent shortening URLs generated by this app
        parsed = urlparse(original_url)
        url_host = parsed.netloc.split(':')[0].lower()
        current_host = request.host.split(':')[0].lower()

        if url_host == current_host:
            short_path = parsed.path.strip('/')

            with sqlite3.connect(DATABASE) as conn:
                cursor = conn.cursor()
                cursor.execute(
                    "SELECT id FROM urls WHERE short_code = ?",
                    (short_path,)
                )
                if cursor.fetchone():
                    return render_template(
                        'index.html',
                        error_message="This URL is already shortened."
                    ), 400

        # Validate custom alias
        if custom_code:
            if len(custom_code) > 30:
                return render_template(
                    'index.html',
                    error_message="Custom code must be 30 characters or less."
                ), 400
            if not re.match(r'^[a-zA-Z0-9_-]+$', custom_code):
                return render_template(
                    'index.html',
                    error_message="Only letters, numbers, hyphens, and underscores are allowed."
                ), 400

        with sqlite3.connect(DATABASE) as conn:
            cursor = conn.cursor()
            # Check duplicate URL
            cursor.execute(
                "SELECT short_code FROM urls WHERE original_url = ?",
                (original_url,)
            )
            existing = cursor.fetchone()

            if existing and not custom_code:
                short_code = existing[0]
                message = "Short URL already exists."
            else:

                if custom_code:
                    cursor.execute(
                        "SELECT id FROM urls WHERE short_code = ?",
                        (custom_code,)
                    )
                    if cursor.fetchone():
                        return render_template(
                            'index.html',
                            error_message="Custom short URL already taken."
                        ), 400
                    short_code = custom_code

                else:
                    while True:

                        short_code = generate_short_code()
                        cursor.execute(
                            "SELECT id FROM urls WHERE short_code = ?",
                            (short_code,)
                        )
                        if not cursor.fetchone():
                            break
                cursor.execute(
                    "INSERT INTO urls (original_url, short_code) VALUES (?, ?)",
                    (original_url, short_code)
                )
                conn.commit()

                message = "New short URL created."

        short_url = request.host_url + short_code
    return render_template('index.html',short_url=short_url,message=message)

# Redirect Route
@app.route('/<short_code>')
def redirect_url(short_code):

    with sqlite3.connect(DATABASE) as conn:
        cursor = conn.cursor()
        cursor.execute(
            "SELECT original_url FROM urls WHERE short_code = ?",
            (short_code,)
        )
        result = cursor.fetchone()

        if result:
            cursor.execute(
                "UPDATE urls SET clicks = clicks + 1 WHERE short_code = ?",
                (short_code,)
            )

            conn.commit()

            return redirect(result[0])

    return "URL not found", 404

# Analytics Dashboard
@app.route('/stats')
def stats():

    with sqlite3.connect(DATABASE) as conn:
        cursor = conn.cursor()
        cursor.execute("""
            SELECT id, original_url, short_code, clicks
            FROM urls
            ORDER BY clicks DESC, id ASC
        """)

        data = cursor.fetchall()

    total_urls = len(data)
    total_clicks = sum(row[3] for row in data)

    return render_template('stats.html',data=data,total_urls=total_urls,total_clicks=total_clicks)

# Delete URL
@app.route('/delete/<int:url_id>', methods=['POST'])
def delete_url(url_id):

    with sqlite3.connect(DATABASE) as conn:
        cursor = conn.cursor()
        cursor.execute(
            "DELETE FROM urls WHERE id = ?",
            (url_id,)
        )
        conn.commit()

    return redirect('/stats')

# Run Application
if __name__ == '__main__':
    init_db()
    app.run(debug=True)